apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: 703997246287.dkr.ecr.us-east-1.amazonaws.com/web3app:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080